name: Publish to PyPi

on:
  push:
    branches:
      - main

env:
    TWINE_PYPI_PASSWORD: ${{ secrets.TWINE_PYPI_PASSWORD }}
    TWINE_TESTPYPI_PASSWORD: ${{ secrets.TWINE_TESTPYPI_PASSWORD }}

jobs:
  publish_to_testpypi:
    name: Publish to TestPyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build and publish to TestPyPi
        run: |
          pwsh ./upload_test_pypi.ps1

  publish_to_pypi:
    name: Publish to PyPi (Manual Approval)
    runs-on: ubuntu-latest
    needs: publish_to_testpypi
    if: github.ref == 'refs/heads/main'       

    environment:
      name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build and publish to PyPi
        run: |
          pwsh ./upload_pypi.ps1